# Generated by Django 5.0.7 on 2024-07-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bloom_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course_outcome',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unit_no',
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level10',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level11',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level12',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level13',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level14',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level15',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level16',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level17',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level18',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level19',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level20',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level21',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level22',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level3',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level4',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level5',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level6',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level7',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level8',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level9',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome10',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome11',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome12',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome13',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome14',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome15',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome16',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome17',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome18',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome19',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome20',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome21',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome22',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome5',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome6',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome7',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome8',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_outcome9',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text10',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text11',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text12',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text13',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text14',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text15',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text16',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text17',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text18',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text19',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text20',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text21',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text22',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text4',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text5',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text6',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text7',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text8',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text9',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no1',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no10',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no11',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no12',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no13',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no14',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no15',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no16',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no17',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no18',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no19',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no2',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no20',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no21',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no22',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no3',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no4',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no5',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no6',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no7',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no8',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit_no9',
            field=models.CharField(choices=[('1', '1st Unit'), ('2', '2nd Unit'), ('3', '3rd Unit'), ('4', '4th Unit'), ('5', '5th Unit')], default=None, max_length=1, null=True),
        ),
    ]
