# Generated by Django 5.0.7 on 2024-07-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentanswers',
            old_name='assignment',
            new_name='assignment_question',
        ),
    ]
