# Generated by Django 5.0.7 on 2024-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_question_bloom_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_outcome1',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome10',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome11',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome12',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome13',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome14',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome15',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome16',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome17',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome18',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome19',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome2',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome20',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome21',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome22',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome3',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome4',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome5',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome6',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome7',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome8',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_outcome9',
            field=models.CharField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')], default=1, max_length=10),
        ),
    ]
