# Generated by Django 5.0.7 on 2024-07-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentQuestions',
            new_name='AssignmentQuestion',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
