# Generated by Django 5.0.7 on 2024-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_assignmentquestions_assignmentquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='unit',
            field=models.CharField(max_length=40),
        ),
    ]
