# Generated by Django 5.0.7 on 2024-07-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_note_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.subject'),
        ),
    ]
