# Generated by Django 5.0.7 on 2024-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.RemoveField(
            model_name='examdetail',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='examdetail',
            name='academic_year_end',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='academic_year_start',
            field=models.IntegerField(default=2024),
        ),
    ]
