# Generated by Django 5.0.7 on 2024-07-25 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_custompermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_start', models.IntegerField()),
                ('academic_year_end', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='examdetail',
            name='academic_year_end',
        ),
        migrations.RemoveField(
            model_name='examdetail',
            name='academic_year_start',
        ),
        migrations.AddField(
            model_name='examdetail',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.academicyear'),
        ),
    ]
