# Generated by Django 5.0.7 on 2024-07-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_examdetail_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pdf',
            field=models.FileField(null=True, upload_to='staff/resume'),
        ),
    ]
