# Generated by Django 5.0.7 on 2024-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_pdf_staff_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='name',
            field=models.CharField(default='Unit 1 Assignment', max_length=40),
        ),
    ]
