# Generated by Django 5.0.7 on 2024-07-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_assignmentquestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.subject'),
        ),
    ]
