# Generated by Django 5.0.7 on 2024-07-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_assignmentquestion_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='unit',
            new_name='name',
        ),
    ]
