# Generated by Django 5.0.7 on 2024-07-25 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_unit_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
