# Generated by Django 5.0.7 on 2024-07-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_note_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='related_documents',
            field=models.FileField(default=None, upload_to='leave/staff'),
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='related_documentz',
            field=models.FileField(default=None, upload_to='leave/student'),
        ),
        migrations.CreateModel(
            name='AdminAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
