# Generated by Django 5.0.7 on 2024-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_leavereportstaff_related_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='related_documents',
            field=models.FileField(default=None, null=True, upload_to='leave/staff'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='related_documentz',
            field=models.FileField(default=None, null=True, upload_to='leave/student'),
        ),
    ]
