# Generated by Django 5.0.7 on 2024-07-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_leavereportstaff_related_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=9962526764, max_length=10),
        ),
    ]
