# Generated by Django 5.0.7 on 2024-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_student_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='faculty_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(default=9962526764, max_length=10),
        ),
    ]
