# Generated by Django 5.0.7 on 2024-07-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_staff_faculty_id_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to='attendance/'),
        ),
    ]
