# Generated by Django 5.0.7 on 2024-07-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_attendance_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='pdf',
            field=models.FileField(null=True, upload_to='assignments/questions'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (1, 'Present'), (2, 'On Duty Internal'), (3, 'On Duty External'), (4, 'Pending'), (5, 'Present (OD)')], default=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='faculty_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.FileField(upload_to='notice')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.department')),
                ('uploaded_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
