# Generated by Django 5.0.7 on 2024-07-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_assignmentquestion_pdf_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.department'),
        ),
    ]
