# Generated by Django 5.0.7 on 2024-07-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_admin_admin_user_rename_admin_staff_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstudent',
            old_name='related_documentz',
            new_name='related_documents',
        ),
    ]
