# Generated by Django 5.0.7 on 2024-07-27 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_rename_related_documentz_leavereportstudent_related_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='related_documents',
            field=models.FileField(upload_to='leave/staff'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='related_documents',
            field=models.FileField(default=django.utils.timezone.now, upload_to='leave/student'),
            preserve_default=False,
        ),
    ]
