# Generated by Django 5.0.7 on 2024-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_leavereportstaff_related_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='rejection_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='rejection_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
