# Generated by Django 5.0.7 on 2024-07-28 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_rename_name_note_title_alter_question_bloom_level1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
    ]
