# Generated by Django 5.0.7 on 2024-07-28 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='mentor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
    ]
