# Generated by Django 5.0.7 on 2024-07-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_classlist_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='mentor',
            new_name='incharge',
        ),
    ]
